"""Replay the FULL capture cache through the real pipeline (FinBERT) and the stress trigger rules, and report which
real headlines would have triggered stress runs.

Time is simulated from each document's timestamp, so the 30-minute cooldown behaves as it would have live.
Writes data/eval/trigger_replay_<label>.json and prints a table.

Usage:  python scripts/replay_trigger_report.py --label before|after
"""

from __future__ import annotations

import argparse
import inspect
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.config import Settings, get_settings  # noqa: E402
from portfolio.loader import issuer_exposures, load_portfolio  # noqa: E402
from portfolio.stress_engine import StressEngine  # noqa: E402
from risk_engine.impact_scoring.corroboration import CorroborationTracker  # noqa: E402
from risk_engine.impact_scoring.scorer import ImpactScorer  # noqa: E402
from risk_engine.ingestion.replay import load_cached_documents  # noqa: E402
from risk_engine.pipeline import RiskPipeline  # noqa: E402
from risk_engine.sentiment.finbert import SentimentEngine  # noqa: E402


def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    ap = argparse.ArgumentParser()
    ap.add_argument("--label", required=True)
    args = ap.parse_args()

    s = get_settings()
    docs = load_cached_documents(s.cache_path)
    portfolio = load_portfolio(s)
    pipe = RiskPipeline(sentiment=SentimentEngine(Settings(sentiment_backend="finbert")),
                        scorer=ImpactScorer(exposures=issuer_exposures(portfolio)),
                        corroboration=CorroborationTracker(6))
    engine = StressEngine(s, portfolio)
    now = {"t": 0.0}
    engine.triggers.clock = lambda: now["t"]
    takes_source = "source" in inspect.signature(engine.triggers.evaluate).parameters

    runs, candidates = [], []
    by_id = {d.doc_id: d for d in docs}
    for i in range(0, len(docs), 32):
        for sig in pipe.process_batch(docs[i : i + 32], skip_rejected=True):
            now["t"] = sig.timestamp.timestamp()
            doc = by_id[sig.doc_id]
            src = (doc.imitated_source or doc.source).value
            cands = engine.triggers.candidates(sig, source=src) if takes_source else engine.triggers.candidates(sig)
            for c in cands:
                candidates.append({"scenario": c.scenario, "source": src, "headline": doc.title[:140]})
            fired = engine.triggers.evaluate(sig, source=src) if takes_source else engine.triggers.evaluate(sig)
            for d in fired:
                runs.append({"scenario": d.scenario, "scope": d.scope_issuer_id or "MARKET", "kind": d.kind,
                             "source": src, "impact": sig.impact_score, "event": sig.event_type,
                             "entity": sig.company, "headline": doc.title[:140], "rule": d.rule})

    out = {"label": args.label, "documents": len(docs), "rule_candidates": len(candidates), "stress_runs": len(runs),
           "runs_by_kind": dict(Counter(r["kind"] for r in runs)),
           "runs_by_source": dict(Counter(r["source"] for r in runs)), "runs": runs,
           "suppressed_by_cooldown": len(engine.triggers.suppressed)}
    path = ROOT / "data" / "eval" / f"trigger_replay_{args.label}.json"
    path.write_text(json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"[{args.label}] {len(docs)} cached docs → {len(candidates)} rule candidates → {len(runs)} stress runs "
          f"(after cooldown); by kind {out['runs_by_kind']}; by source {out['runs_by_source']}")
    for r in runs:
        print(f"  {r['kind']:<13} {r['scenario']:<26} {r['source']:<11} {r['impact']:>4} {r['event']:<13} "
              f"{r['entity'][:16]:<16} {r['headline'][:90]}")
    print(f"wrote {path.relative_to(ROOT)}")
    write_comparison()
    return 0


def write_comparison() -> None:
    """docs/trigger_replay.md from trigger_replay_before.json and trigger_replay_after.json (when both exist)."""
    paths = [ROOT / "data" / "eval" / f"trigger_replay_{x}.json" for x in ("before", "after")]
    if not all(p.exists() for p in paths):
        return
    b, a = (json.loads(p.read_text(encoding="utf-8")) for p in paths)
    after_heads = {r["headline"] for r in a["runs"]}
    before_heads = {r["headline"] for r in b["runs"]}
    removed = [r for r in b["runs"] if r["headline"] not in after_heads]
    added = [r for r in a["runs"] if r["headline"] not in before_heads]
    lines = [
        "# Stress-trigger replay over the full real cache",
        "",
        "Generated by `scripts/replay_trigger_report.py` (FinBERT, full pipeline, trigger rules; time simulated from "
        "document timestamps so the 30-minute cooldown behaves as live). Inputs: every CACHED_REAL document in the "
        "local capture cache. Stress results are simulated (illustrative model).",
        "",
        "| | before fixes | after fixes |",
        "|---|---:|---:|",
        f"| documents replayed | {b['documents']} | {a['documents']} |",
        f"| trigger-rule candidates | {b['rule_candidates']} | {a['rule_candidates']} |",
        f"| stress runs (after cooldown) | {b['stress_runs']} | {a['stress_runs']} |",
        f"| systemic runs | {b['runs_by_kind'].get('systemic', 0)} | {a['runs_by_kind'].get('systemic', 0)} |",
        f"| idiosyncratic runs | {b['runs_by_kind'].get('idiosyncratic', 0)} | "
        f"{a['runs_by_kind'].get('idiosyncratic', 0)} |",
        f"| runs triggered by social posts | "
        f"{sum(v for k, v in b['runs_by_source'].items() if k not in ('google_news', 'finnhub', 'gdelt'))} | "
        f"{sum(v for k, v in a['runs_by_source'].items() if k not in ('google_news', 'finnhub', 'gdelt'))} |",
        "",
        "Fixes: systemic stress only from news sources (social posts only corroborate); a MARKET-wide Macroeconomic/"
        "Geopolitical call needs >= 2 distinct matched patterns; figurative 'war' guards; fuzzy entity match needs all "
        "distinctive tokens (\"SEC\" is no longer the Government of India's \"G-Sec\").",
        "",
        f"## Runs removed by the fixes ({len(removed)})",
        "",
        "| kind | scenario | source | headline |",
        "|---|---|---|---|",
    ]
    lines += [f"| {r['kind']} | {r['scenario']} | {r['source']} | {r['headline'].replace('|', '/')} |" for r in removed]
    lines += ["", "Not every removed run was a false positive: the >= 2-pattern rule also drops some genuine "
              "single-cue market stories (recall cost). Read the list above before relying on the totals.", "",
              f"## Runs that appear only after the fixes ({len(added)})", "",
              "Usually a cooldown side effect: a removed earlier run no longer blocks a later run of the same "
              "scenario.",
              "", "| kind | scenario | source | headline |", "|---|---|---|---|"]
    lines += [f"| {r['kind']} | {r['scenario']} | {r['source']} | {r['headline'].replace('|', '/')} |" for r in added]
    lines += ["", f"## Runs that still trigger ({a['stress_runs']})", "",
              "| kind | scenario | source | impact | headline |", "|---|---|---|---:|---|"]
    lines += [f"| {r['kind']} | {r['scenario']} | {r['source']} | {r['impact']} | {r['headline'].replace('|', '/')} |"
              for r in a["runs"]]
    lines += ["", "Known remaining false positives (not addressed by these fixes): positive regulatory/court news "
              "still fires idiosyncratic stress (e.g. 'Adani … shares rise as the US Court dismisses …', "
              "'Jio IPO nears launch: … SEBI clears path'); 'Verdict' in an analyst headline reads as Litigation; "
              "rate-CUT headlines map to the rate-SHOCK (hike) scenario family because the spec defines only hike "
              "scenarios."]
    newline = chr(10)
    (ROOT / "docs" / "trigger_replay.md").write_text(newline.join(lines) + newline, encoding="utf-8")
    print("wrote docs/trigger_replay.md")


if __name__ == "__main__":
    sys.exit(main())
